services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443" #pourquoi pas 8443:443 ?
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
    networks:
      - inception

volumes:
  mariadb_data:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wordpress_data:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

# par defaut deja un reseau bridge local permettant d'isoler mais plus explicite
networks:
  inception:
    driver: bridge