From debian:bullseye

Run apt-get install nginx -y && apt-get install php-fpm

Copy ./conf/
Copy ./tools/script.sh 

#si fichier colle a la place precemement alors lance ce script 
# ou ne pas remplacer le fichier mais venir le modifier depuis le script
ENTRYPOINT ["/usr/local/bin/script.sh"] 